name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: somethingsecret
      PGDATABASE: accord
      CI: true
      ACCESS_TOKEN_KEY: secret
      REFRESH_TOKEN_KEY: terces
      ACCESS_TOKEN_AGE: 3600

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: somethingsecret
          POSTGRES_DB: accord

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      
      - name: Migrate database
        run: npm run migrate up

      - name: Make publish.sh executable
        run: chmod +x ./scripts/publish.sh
      
      - name: Build and release
        run: npm run release

  deploy:
    name: Deploy to Azure Container Apps
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: my-resource-group
          containerAppName: my-container-app
          imageToDeploy: ghcr.io/dedyurama-id/accord_be:latest
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.GHCR_USERNAME }}
          registryPassword: ${{ secrets.GHCR_TOKEN }}

